### PR TITLE
Use smalltalkCI

### PR DESCRIPTION
**Pull request by fniephaus**
Hi @svenvc,
[Doesn't look](https://travis-ci.org/svenvc/ston) like you have Travis CI enabled, but this runs the STON tests with [smalltalkCI](https://github.com/hpi-swa/smalltalkCI) on different Pharo images (see [here](https://travis-ci.org/fniephaus/ston/builds/177823494)).

Fabio

### CODE REVIEW

**Comment by svenvc** [comment]
Fabio,

I merged your pull request. What now ?

Sven

**Comment by fniephaus** [comment]
Can you [enabled Travis CI](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A) for this project?

**Comment by svenvc** [comment]
I enabled & activated scenic/ston ...

**Comment by fniephaus** [comment]
Thanks, the next time you push something, Travis should run the ston tests.
https://travis-ci.org/svenvc/ston/

**Comment by svenvc** [comment]
Very nice, thank you!

**Pull request merged**
