### PR TITLE
improve #stonName: comment

### PR DESCRIPTION
**Pull request by jecisc**
I had a hard time with ston because I used strings in #stonName. I improved the comment.

### CODE REVIEW

**Comment by svenvc** [comment]
Maybe this is a bug, I should check out myself what happens and how it fails.

**Comment by jecisc** [comment]
@svenvc 
The mapper use #== to detect the name and it read Symbol from the file. So, if #stonName does not return a symbol there is a problem. 
It is in STONReader>>lookupClass:

**Comment by svenvc** [comment]
That should probably be changed to #= ...

**Comment by svenvc** [comment]
Should be fixed in https://github.com/svenvc/ston/commit/94d62c7dbc7bf6212a85ad8ac577e701f2448936

Now the following returns a string

    STONTestUser3 stonName.

And you can still do

    STON fromString: (STON toString: STONTestUser3 dummy).

**Pull request closed without merging**
